export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const ADD_BUSINESS = 'ADD_BUSINESS';
export const SET_CURRENT_BUSINESS = 'SET_CURRENT_BUSINESS';
export const SET_MY_BUSINESSES = 'SET_MY_BUSINESSES';
export const DELETE_BUSINESS = 'DELETE_BUSINESS';
export const EDIT_BUSINESS = 'EDIT_BUSINESS';
